import re #regex
import os
from unidecode import unidecode #removes accented characters
from metaphone import doublemetaphone #converts a name into phonetics, allows for fuzzy name searching

student_List = [
    ("U1D40QFD4", "Adam Braus"),
    ("U1HBKMW8Y", "Alan Davis"),
    ("U1NCM4VME", "Mike Kane"),
    ("U1T2Q3G81", "Michael Loubier"),
    ("U1U2T6HT6", "Shannon Bailey"),
    ("U1UTEGPU6", "Carlos Diez"),
    ("U1VDXDV0X", "Casey Spencer"),
    ("U1YM6H8MA", "Tassos Lambrou"),
    ("U237ELPUH", "Jeremy Rossmann"),
    ("U2481KKBM", "Komal Desai"),
    ("U264ANGAE", "Bob De Kort"),
    ("U28S64ZJ5", "Mitchell Hudson"),
    ("U298FAPT7", "Susan Nesbitt"),
    ("U2B6Q2SVB", "Corey Harrilal"),
    ("U2C90DSLF", "Dion Larson"),
    ("U2C90LDS9", "Dan Morse"),
    ("U2FCY2FBR", "Ashu Desai"),
    ("U2QTVG278", "Jordan Arnesen"),
    ("U41MM2A1Z", "Chase Wang"),
    ("U48LVBV34", "Eliel Gordon"),
    ("U4CEBV4SW", "Mona Desai"),
    ("U6WMDD6U8", "Kaichi Momose"),
    ("U6WQK3Q73", "Juan Hurtado"),
    ("U6WRNH1JM", "Christopher Taylor"),
    ("U6X9KPH7C", "Jeff Chiu"),
    ("U6X9L8VAN", "Novan Adams"),
    ("U6X9L8VAN", "Donny Adams"),
    ("U6XA0UA10", "Yves Songolo"),
    ("U6XCP1NLU", "Ferdinand Cruz"),
    ("U6XCTHTQQ", "Sam Galizia"),
    ("U6XDGCKFF", "Matthew Harrilal"),
    ("U6XDKSREZ", "Tony Cioara"),
    ("U6XDV6CVA", "Melody Yang"),
    ("U6XE4NNSZ", "Sky Xu"),
    ("U6XJLPQ9Y", "Johnathan Chen"),
    ("U6XRWEQGY", "Chris Mauldin"),
    ("U6XV0FFEW", "Alirie Gray"),
    ("U6Y6KU78W", "Uchenna Aguocha"),
    ("U6YCJRXGF", "Duncan MacDonald"),
    ("U6YCV95L7", "Ansel Bridgewater"),
    ("U6YD3BYBD", "Andrew Tsukuda"),
    ("U6YFC7074", "James Rezendes"),
    ("U6YGZN9HD", "Egon Fiedler"),
    ("U6YHCA79U", "Elliot Briant"),
    ("U6YHKG1RQ", "Elmer Astudillo"),
    ("U6YMF5THV", "Erik Perez"),
    ("U6YMU9QCF", "Aakash Sudhakar"),
    ("U6YMU9QCF", "Kash Sudhakar"),
    ("U6YP200VB", "Phyllis Wong"),
    ("U6YV4A45C", "Tia King"),
    ("U6Z4KNWCD", "Kendra Moore"),
    ("U6Z5ZDKP1", "Jake Tran"),
    ("U6Z9LHPEH", "Mondale Felix"),
    ("U6ZCE0AKG", "Rohan Mishra"),
    ("U703HM5PY", "Justin Sitter"),
    ("U72SB0WG6", "Sunny Ouyang"),
    ("U74A620U8", "Megan Doepker"),
    ("U7U7MS551", "Michael Ashby"),
    ("U7V12NBSR", "Alena Dagneau"),
    ("U8M6VPKUZ", "Erick Sanchez"),
    ("U8MP28D9S", "Joe Rezendes"),
    ("U8NHWGBGW", "Shane Austrie"),
    ("U8NHWRX0W", "Parnell Kelley"),
    ("U8NMLKGDU", "Jayce Azua"),
    ("U8X0NTGER", "Mateusz Wijas"),
    ("U90HP2ZT6", "Lucas Arruda"),
    ("U916G04LB", "Miki Nomura"),
    ("U9HT8DV8S", "Erin"),
    ("U9PA0BZQW", "Megan Dias"),
    ("U9W8R4A2W", "Chloe Darsch"),
    ("UBJU66HLG", "Courtney Bell"),
    ("UBZLA95GV", "Adriana Gonzalez"),
    ("UC36F4P2M", "Dani Roxberry"),
    ("UC45RJQ7M", "Anne Spalding"),
    ("UC7PP1PTR", "Jen Sikora"),
    ("UCB3G0JKS", "Rinni Swift"),
    ("UCB3PRBME", "Nyapal Gatkuoth"),
    ("UCB58P2V6", "Medi Assumani"),
    ("UCB8SBFJ4", "Joshua Geronimo"),
    ("UCB8T1AG0", "Anna Pawl"),
    ("UCB8U00KA", "Faith Chikwekwe"),
    ("UCB8WCDTJ", "Nathan Pillai"),
    ("UCB8Y9ZQ8", "Timofey Makhlay Kapitsa"),
    ("UCB8YJNBT", "Sukhrob Golibboev"),
    ("UCB91TXS4", "KJ Wilson"),
    ("UCBC6K65P", "Matthew Phraxayavong"),
    ("UCBC9725P", "Sean Glancy"),
    ("UCBD9KCQH", "Jasmine Anderson"),
    ("UCBDA2GGH", "Jacob Haff"),
    ("UCBDBB3LZ", "Tim Kaing"),
    ("UCBDDHX7T", "Connor Cahill"),
    ("UCBDPE94Z", "Dylan Finn"),
    ("UCBHLEZEY", "Javier Mendoza"),
    ("UCBHMLWEQ", "Parker Tenove"),
    ("UCBHQSTB6", "Jackson Ho"),
    ("UCBHS20S0", "Eric Botcher"),
    ("UCBHS9M3N", "Keoni Murray"),
    ("UCBKC02JY", "Nicolai Safai"),
    ("UCBLQF0R1", "Sarin Swift"),
    ("UCBLQTD7V", "Jamie McCrory"),
    ("UCBMZFL4U", "Ricardo Rodriguez"),
    ("UCBP3BYTW", "Erik Batista"),
    ("UCBP4M9C4", "Drew McGowan"),
    ("UCBP5EN5S", "Maximo Hinojosa"),
    ("UCBPUT6AX", "Wenzel Lowe"),
    ("UCBQH1P6E", "Edwin Cloud"),
    ("UCBQJD3NW", "Jaeson Booker"),
    ("UCBQLD4M8", "Jeremy James"),
    ("UCBS1DSF5", "Erica Naglik"),
    ("UCBS25JKD", "Khallil Bailey"),
    ("UCBS25XMZ", "Nolan Kovacik"),
    ("UCBS37LKV", "Victoria Murray"),
    ("UCBS4EW59", "Luc Highwalker"),
    ("UCBS8JUHH", "Makhmud Islamov"),
    ("UCBSELQ2F", "Colleen Ni"),
    ("UCBSELQ2F", "Zhanxi Ni"),
    ("UCC0FMXCJ", "Dacio Romero"),
    ("UCC0GD5V0", "Jasmine Humbert"),
    ("UCC0GL52N", "Stephanie Cherubin"),
    ("UCC0H4UJE", "Lucia Reynoso"),
    ("UCC0HC7D0", "Marianna Campbell"),
    ("UCC0KLBPU", "Raymond Wu"),
    ("UCC37PD6D", "Anisha Jain"),
    ("UCC4RHFU5", "Ryan Nguyen"),
    ("UCC4RUF4M", "Jonathan Kopp"),
    ("UCC4S13NZ", "Cherish Kim"),
    ("UCC4SJBL5", "Samuel Harrison"),
    ("UCC4SUSHK", "Ramon Geronimo"),
    ("UCC4TPF5K", "Drake Vorndran"),
    ("UCC4TPF5K", "Ki Vorndran"),
    ("UCC4U4V53", "Salvador Becerra"),
    ("UCCL1R3EZ", "Ali Shalabi"),
    ("UCCRGTD0X", "Thomas Lee"),
    ("UCCS7HWGP", "Erick Espinoza"),
    ("UCCS7HWGP", "Wesley Espinoza"),
    ("UCCSGECPJ", "Ikey Benzaken"),
    ("UCCTF62ET", "Ryan Smith"),
    ("UCD1J9LDV", "Fode Diop"),
    ("UCD1JMBMM", "Aktar Zaman"),
    ("UCD1JVCJ3", "Betsy Bailey"),
    ("UCD4Y1DCN", "Jamar Gibbs"),
    ("UCD53TKCN", "Vincenzo Marcella"),
    ("UCD9D1YH4", "Kuan-Ying Fang"),
    ("UCDAE5GSJ", "Stephen Ouyang"),
    ("UCDAETD5L", "Asim Zaidi"),
    ("UCDAF4FV4", "Seve Badajoz"),
    ("UCDAJD4F8", "Zurich Okoren"),
    ("UCDAKSB7Y", "Ruhsane Sawut"),
    ("UCDAMHRDL", "William Bogans"),
    ("UCDPM021J", "Noah Woodward"),
    ("UCFCFQ7KK", "Henry Bowe"),
    ("UCFCGA3C1", "Connor Oswold"),
    ("UCH838UC9", "Jake Shams"),
    ("UCHK87XEJ", "Ebonne Cabarrus"),
    ("UCHMQH2HE", "Milad Toutounchian"),
    ("UCJ72FALU", "Caroline Virani"),
    ("UCMTPELBC", "Jeff D'Andria"),
    ("UCN7DEGP7", "Bill Phillips"),
    ("UCPQD5NHM", "Matt Davis"),
    ("UCR0ANW5T", "Stacey Garcia"),
    ("UCZQFV9BR", "Amy Young"),
    ("UD44P4YRE", "Devery Doran"),
    ("UD57U4QAV", "Sarah George"),
    ("UEHTXECFN", "Ryan Lamvik"),
    ("UEPUV52GL", "Ian Birnam"),
    ("UF83RJTHD", "Brian Nguyen"),
    ("UFBTRMEBV", "Richard Kalish"),
    ("UFCF6M0TE", "Thomas Vandegriff"),
    ("UFHMAU6Q3", "Leslie Kim"),
    ("UFSH2CGLW", "Marianne Rogoff"),
    ("UFY73CVKJ", "Henry Shreibman"),
    ("UGBPGM2P2", "Ryan Smith"),
    ("UGK8D1R8E", "Buay Tut"),
    ("UHJFRH545", "Eric Deng"),
    ("UHK2P9EPR", "Madelyn Martin"),
    ("UJK39Q5ME", "Doreen Leong"),
    ("UJKNLUF9A", "Charlie Taibi"),
    ("UJMHLRJRJ", "Elizabeth Swander"),
    ("UJS6MLZJM", "Ben Ambrogi"),
    ("UJTDUJXU3", "Daniel May"),
    ("UJU7FSE4C", "Tania Gidney"),
    ("UJUJZANKD", "Lindsey Dean"),
    ("UK42V03K9", "Precious Listana"),
    ("UK45MB3NG", "Joe Zolnoski"),
    ("UK6TA5V1D", "Sean Lawrence"),
    ("UKACCG1J6", "Michelle Blackburn"),
    ("UKC6Y5MPH", "Siebe Jan Stoker"),
    ("UKMGT7BKJ", "Meredith Murphy"),
    ("UKR7GN6FK", "Simon Kronenberg"),
    ("UL8JXU0CR", "Ellie MacBride"),
    ("UM1ESSU94", "Jess Dahmen"),
    ("UM4KA8YGN", "Trisha Regine Fuerte"),
    ("UMB7Q5A1E", "Celisse Randolph"),
    ("UMBUDNURY", "Bradley Van Alstyne"),
    ("UMCUQ3Q3U", "Mo Drame"),
    ("UMCUQ56TC", "Henry Calderon"),
    ("UMCUQAZ6W", "Samuel Folledo"),
    ("UMCUQBYLA", "Ricky Nguyen"),
    ("UMCUQDCEN", "Genji Tapia"),
    ("UMCUQF28J", "Kye Williams"),
    ("UMCUQJ3U2", "Hassan El-Amin"),
    ("UMCUQRMGS", "Louis Dweck"),
    ("UMCURA7A6", "George Aoyagi"),
    ("UMCURC0LS", "Jonasz Rice"),
    ("UMCURHL9Y", "Shaan Hurley"),
    ("UMCURUVK4", "Uyen Nguyen"),
    ("UMCUS202E", "Anjelica Ambrosio"),
    ("UMCUS3A2E", "Stanley Chow"),
    ("UMCUS7998", "Francis Tsang"),
    ("UMCUUSE6P", "Samir Ingle"),
    ("UMCUUUPM1", "Donny Vallejo"),
    ("UMCUV3MGT", "Zain Raza"),
    ("UMCUVMK5Z", "Jose Arellanes Aldaco"),
    ("UMCUW0DKM", "Ryan Keys"),
    ("UMCUW80F5", "Jarquevious Nelson"),
    ("UMCUWBJ5R", "Jeric Hunter"),
    ("UMCUWBK9R", "Liya Tilahun"),
    ("UMCUWDH35", "Joanelly Cruz"),
    ("UMCUWKRGB", "Franklin Phan"),
    ("UMCUWMFEF", "Sebastian Abarca"),
    ("UMCUWN1SP", "vladyslav nykoliuk"),
    ("UMCUWR9K5", "Ruk Lakhani"),
    ("UMCUWSAHZ", "Megan Obryan"),
    ("UMCUWSM7V", "Lauren Dutton"),
    ("UMCUWSY2F", "Cao Mai"),
    ("UMEPZ3JQK", "Kaniet Oskonbaev"),
    ("UMJ1BB3EV", "Anas Bellouzi"),
    ("UMJ1BBQPK", "Gary Frederick"),
    ("UMJ1BD8P3", "Aucoeur Ngo"),
    ("UMJ1BNSQZ", "Nicole Rocha"),
    ("UMJ1C1YHX", "Pasang Lama Tamang"),
    ("UMJ1C2XTK", "Gabriel Lee"),
    ("UMJ1C5TPB", "Max Finn"),
    ("UMJ1CUB97", "Xing Ye"),
    ("UMJ1CUFNV", "Kevin Meyers"),
    ("UMJ1D157B", "Diyar Kudrat"),
    ("UMJ1D3DL1", "Brandon Christoffer"),
    ("UMJ1D560Z", "Angelina Olmedo"),
    ("UMJ1D7EV7", "Tristan Fossan"),
    ("UMJ1DG4HX", "Elbert Ostolaza"),
    ("UMPU6AU84", "Anthony Protho"),
    ("UMPU6PRFW", "Ike Holzmann"),
    ("UMPU6QSNQ", "Aleia Knight"),
    ("UMPU6TVDJ", "Beck Haywood"),
    ("UMPU759T6", "Andrew Reyes"),
    ("UMPU7650C", "Jerome Schmidt"),
    ("UMPU7708L", "Patrick Kelly"),
    ("UMPU7QL4C", "Rediet Abere"),
    ("UMPU7UG0L", "John Miner"),
    ("UMPU813B6", "Ben Simpson"),
    ("UMPU81SDA", "Ian Rones"),
    ("UMPU8716G", "Omar Sagoo"),
    ("UMPU88GBW", "Subal Pant"),
    ("UMPU88U8L", "Christian Galkowski"),
    ("UMPU8AF3N", "Luke Harrison"),
    ("UMPU8BCAY", "Jorge Gallegos"),
    ("UMQCGRM4Y", "Jessica Trinh"),
    ("UMQCH2AM6", "Joey Gaitan"),
    ("UMQCH3280", "Andre Williams"),
    ("UMQCHL2N4", "Gideon Crawley"),
    ("UMQCHSB6C", "Sandy Camilo"),
    ("UMQCJ1D4Y", "Tanner York"),
    ("UMQCJA9UY", "Padyn Riddell"),
    ("UMQCJBA00", "Chris Barnes"),
    ("UMQCJC9QQ", "Tyler Holland"),
    ("UMQCJCMA4", "Alex Gray"),
    ("UMQCJFDUG", "Deer Brinkley"),
    ("UMQCJHJ72", "Shashwat Prajjwal"),
    ("UMQCJJ6DN", "Mark Kim"),
    ("UMQCNSLER", "Tasfia Addrita"),
    ("UMQCP0VA9", "Ashab Siddiqui"),
    ("UMQCP2NF7", "Daniel Duque"),
    ("UMQCP40NR", "Gonzo Birrueta"),
    ("UMQCP4ZFF", "Anika Morris"),
    ("UMQCP6MQV", "Dom Holder"),
    ("UMQCPF0G5", "Ben Lafferty"),
    ("UMQCPQ2MT", "Christopher Francisco"),
    ("UMQCQ9LH3", "Konstantin Kishinsky"),
    ("UMQCQBM4M", "Jibryll Brinkley"),
    ("UMQCQDXPX", "Youssef Sawiris"),
    ("UMQCQE3AR", "Anastasia Gallardo"),
    ("UMQCQGA3X", "Ryan Hopkins"),
    ("UMQCQJ5GV", "Ivan Hall"),
    ("UMQCQJZTP", "Dahveyea Cowan"),
    ("UMQCQL9EH", "Jon Infante"),
    ("UMQCQQLSZ", "ChelseaAnne Castelli"),
    ("UMQCQURKP", "John Montejano"),
    ("UMQCQV3C5", "Luke Parker"),
    ("UMQCZ816H", "Muhammad Tifak"),
    ("UMQKDDZV3", "Constantino"),
    ("UMRF0K90C", "Abhishek Kulkarni"),
    ("UMRUWBHCM", "Wyatt Happ"),
    ("UMS8J6KNK", "Kento Murata"),
    ("UMS8JC7RD", "Andrey Novichkov"),
    ("UMS8JQ2ET", "Mario McGee"),
    ("UMS8K32K1", "Thom d'Olanie"),
    ("UMS8KA2J3", "Christian Lenberger"),
    ("UMS8KFR63", "Abdullah Noori"),
    ("UMS8KNNR5", "William Chadwick"),
    ("UMS8KPZFZ", "Farhan Begg"),
    ("UMS8KSC6T", "Audaris Blades"),
    ("UMS8KSZ2T", "Alex Barksdale"),
    ("UMS8KTKSB", "Kabsa Abdi"),
    ("UMSHX8W0N", "Nick Kearns"),
    ("UMSHXC0G6", "Fritz Heider"),
    ("UMSHXES6S", "Arvin Seifipour"),
    ("UMSHXH0BG", "Nyein Chan Aung"),
    ("UMSHXH0BG", "Ninja Aung"),
    ("UMSHXSVML", "Jack Katzer"),
    ("UMSHY8D8W", "Jason McGee"),
    ("UMSHYFHE2", "David Evans"),
    ("UMSHYM1GW", "Parker Paisley"),
    ("UMSHYP0VC", "Ariane Evans"),
    ("UMSHYS4BG", "Alanna Noguchi"),
    ("UMSHZAUQN", "Elaine Music"),
    ("UMSHZETAA", "Chudier"),
    ("UMTQS1139", "Mark Pham"),
    ("UMUNA710V", "Shoha Abdullaev"),
    ("UMUU7JCJG", "Veronica Fruiht"),
    ("UMVCJFA3S", "Catherine Borg"),
    ("UMW6HJV1N", "Naomi Alterman"),
    ("UN3F9JLKW", "Lisa Tran"),
    ("UNXF45NDS", "David Elbel"),
    ("UPSUK4E8H", "Bianca Nieves"),
    ("UQ0S08A00", "Lauren Massell"),
    ("UQ8336Q8K", "Max Fritzhand")
]

student_Dictionary = {}

def createDictionary():
    """converts our list of students and their unique slack id into a dictionary value with a doublemetaphone key. This allows for fuzzy name search"""
    #Parses the student_List 
    for pair in student_List:
        #Sends each name to be converted into a doublemetaphone
        key = insertName(pair[1])
        #Check if the dictionary item exists, if so, spit out name details to debug unique names are not lost
        #ELSE, add items to our dictionary with the doublemetaphone key, and the (slackID,name) tuple as value
        if student_Dictionary.get(key[0]) != None:
            print(f'key value 0 {key[0]} already exists! \n current name: {pair[1]} \n existing name: {student_Dictionary[key[0]][1]}')
        else:
            student_Dictionary[key[0]] = pair
        if key[1] != "":
            if student_Dictionary.get(key[1]) != None:
                print(f'key value 1 {key[1]} already exists!  \n current name: {pair[1]} \n existing name: {student_Dictionary[key[1]][1]}')
            else:
                student_Dictionary[key[1]] = pair
    #writes the db to file, check where the terminal has run the script (IE project root)
    with open(os.path.join(os.getcwd(),('slack_db')), 'w+') as f:
        print(student_Dictionary, file=f)
    #print (student_Dictionary)

def insertName(name:str = "Mr. Sámuel Falledo"):
    """filters the inserted name string 'Kevin Meyers' and converts it, RETURNs the photetical doublemetaphone 'KFNMRS'"""

    #lowercase
    name = name.lower() #doens't seem to be needed

    #remove accented letters
    name = unidecode(name)

    #remove honorifics?
    # this will work, but it removes everything before a period, not strictly honorifics
    regex = r"\w+\. *(?=\w+)|,[\s\w]*$"
    subst = ""
    name = re.sub(regex, subst, name, 0)

    #expand common english name abbreviations
    # https://en.wiktionary.org/wiki/Appendix:Abbreviations_for_English_given_names

    #sort alphabetically
    sort_name = name.split()
    sort_name.sort()
    name = ' '.join(sort_name)

    #double metaphone conversion
    nameTuple = doublemetaphone(name)

    return nameTuple

if __name__ == "__main__":
    createDictionary() 